/*
 * user_app.c
/* ============================================================================
** Copyright (C) 2020 Infineon. All rights reserved.
**               Infineon Technologies, PSS SYS / DES
** ============================================================================
**
** ============================================================================
** This document contains proprietary information. Passing on and
** copying of this document, and communication of its contents is not
** permitted without prior written authorisation.
** ============================================================================
**
** Created on:  2020-08-19
*/


#include "dtimer_drv.h"
#include "telemetry_drv.h"
#include "regulation_api.h"
#include "faults_api.h"
#include "faults_drv.h"
#include "pmbus_api.h"
#include "pmbus_gpio_control.h"
#include "shasta_hal_vsen.h"
#include "shasta_hal_vcontrol.h"
#include "shasta_hal_pwm.h"
#include "shasta_hal_pid.h"
#include "shasta_hal_scu.h"
#include "shasta_hal_cgu.h"
#include "shasta_hal_rgu.h"
#include "shasta_hal_telem.h"
#include "shasta_hal_common.h"
#include "shasta_hal_fault.h"
#include "shasta_hal_isen.h"
#include "regulation_state_machine_callbacks.h"
#include "pmbus_autogen.h"
#include "pmbus_mfr_autogen.h"
#include "user_app.h"
#include "cmsis_os.h"                   // ARM::CMSIS:RTOS:Keil RTX
#include "cmsis_os_ext.h"                   // ARM::CMSIS:RTOS:Keil RTX ext
#include "log_app.h"             /* Logging of errors */
#include "patch_rom_table.h"
#include "string.h"
#include "add_on_features.h"
#include "uart_drv.h"                // uart driver functions
#include "pmbus_mfr_specific_handlers.h"
/**
 * Main entry point of the user application.  Good place to set breakpoint when debugging a patch.
 */

void patch_pmbus_mfr_autogen_init(void);


void patch_pmbus_mfr_autogen_init(void)
{
	pmbus_mfr_autogen_init();
}

/*
 * iout scale Example
 * Initializes pmbus handle changes related to IOUT_SCALE
 * Function reset specific pmbus handle related to IOUT_SCALE.
 * Refer to user_app/iout_range_patch.xlsx
 */
void patch_pmbus_mfr_autogen_iout_range(void)
{
	pmbus_mfr_autogen_init();

	// initialize and re-map PMBUS handler related to output current scales
	ptr_pmbus_callback[PMBUS_CMDCODE_IOUT_CAL_OFFSET] = patch_PMBUS_HANDLE_IOUT_CAL_OFFSET;
	ptr_pmbus_callback[PMBUS_CMDCODE_IOUT_OC_FAULT_LIMIT] = patch_PMBUS_HANDLE_IOUT_OC_FAULT_LIMIT;
	ptr_pmbus_callback[PMBUS_CMDCODE_IOUT_OC_WARN_LIMIT] = patch_PMBUS_HANDLE_IOUT_OC_WARN_LIMIT;
	ptr_pmbus_callback[PMBUS_CMDCODE_IOUT_UC_FAULT_LIMIT] = patch_PMBUS_HANDLE_IOUT_UC_FAULT_LIMIT;
	ptr_pmbus_callback[PMBUS_CMDCODE_IIN_OC_FAULT_LIMIT] = patch_PMBUS_HANDLE_IIN_OC_FAULT_LIMIT;
	ptr_pmbus_callback[PMBUS_CMDCODE_IIN_OC_WARN_LIMIT] = patch_PMBUS_HANDLE_IIN_OC_WARN_LIMIT;
	ptr_pmbus_callback[PMBUS_CMDCODE_VOUT_DROOP] = patch_PMBUS_HANDLE_VOUT_DROOP;
	ptr_pmbus_callback[PMBUS_CMDCODE_FW_CONFIG_REGULATION] = patch_PMBUS_HANDLE_FW_CONFIG_REGULATION;
	ptr_pmbus_callback[PMBUS_CMDCODE_MFR_IOUT_OC_FAST_FAULT_LIMIT] = patch_PMBUS_HANDLE_MFR_IOUT_OC_FAST_FAULT_LIMIT;
	ptr_pmbus_callback[PMBUS_CMDCODE_MFR_IOUT_APC] = patch_PMBUS_HANDLE_MFR_IOUT_APC;
}

/*
 * Main entry point of the user application.  Good place to set breakpoint when debugging a patch.
 * This will only get executed a single time prior to configuration loading and before RTOS starts
 */
void user_drv_init(void)
{
	memset(&user_data, 0, sizeof(USER_DATA_t));  // ZI the user data

	/* iout scale Example Modification Start */
	patch_rom_table.patch_Telemetry_Sample = patch_Telemetry_Sample;
	/* iout scale Example Modification End */

	// this is the initialization of user pmbus commands autogenerated from pmbus spreadsheet
	ptr_mfr_specific_init = (mfr_specific_init_ptr) patch_pmbus_mfr_autogen_init;

	/* iout scale Example Modification Start */
	ptr_mfr_specific_init = (mfr_specific_init_ptr) patch_pmbus_mfr_autogen_iout_range;
	/* iout scale Example Modification End */

	// set the pointer funtion in init of regulation state machine to user callback setup for each state
	set_module_init_cb(MODULE_REGULATION, regulation_sm_callbacks_init);

	add_on_features_init();
	regulation_sm_callbacks_init();
}





