
/**
 * @file    ./src/user_app/pmbus_mfr_autogen.h
 * @brief   Automatically generated from output of pmbus compile script.
 */

/* ============================================================================
** Copyright (C) 2020 Infineon. All rights reserved.
**               Infineon Technologies, PMM SYS / DES
** ============================================================================
**
** ============================================================================
** This document contains proprietary information. Passing on and
** copying of this document, and communication of its contents is not
** permitted without prior written authorisation.
** ============================================================================
**
** Automatically generated by:  pmbus_xlsx2c.py shasta_pmbus.xlsx
** Created on:  2020-09-14
*/
/*lint -save -e960 */


#ifndef PMBUS_MFR_AUTOGEN_H
#define PMBUS_MFR_AUTOGEN_H

#include <stdint.h>              /* uint*_t */
#include "fw_bool.h"             /* boolean type */
#include "pmbus_autogen.h"




#define PMBUS_CMDCODE_MFR_ADAPTIVE_DEADTIME_THRESHOLD_HYST (0xB1)

/* instantiate the command MFR_ADAPTIVE_DEADTIME_THRESHOLD_HYST.
 */
extern PMBUS_CMD_t PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_HYST;
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_HYST_DATA_LOOP0[2];  	// data array for command loop0
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_HYST_DATA_LOOP1[2];    // data array for command loop1 (pointer if common)
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_HYST_RANGE[2];  	// data array for range (common for loops)

#define PMBUS_CMDCODE_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_1 (0xB2)

/* instantiate the command MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_1.
 */
extern PMBUS_CMD_t PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_1;
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_1_DATA_LOOP0[2];  	// data array for command loop0
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_1_DATA_LOOP1[2];    // data array for command loop1 (pointer if common)
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_1_RANGE[2];  	// data array for range (common for loops)

#define PMBUS_CMDCODE_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_2 (0xB3)

/* instantiate the command MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_2.
 */
extern PMBUS_CMD_t PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_2;
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_2_DATA_LOOP0[2];  	// data array for command loop0
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_2_DATA_LOOP1[2];    // data array for command loop1 (pointer if common)
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_2_RANGE[2];  	// data array for range (common for loops)

#define PMBUS_CMDCODE_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_3 (0xB4)

/* instantiate the command MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_3.
 */
extern PMBUS_CMD_t PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_3;
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_3_DATA_LOOP0[2];  	// data array for command loop0
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_3_DATA_LOOP1[2];    // data array for command loop1 (pointer if common)
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIME_THRESHOLD_LEVEL_3_RANGE[2];  	// data array for range (common for loops)

#define PMBUS_CMDCODE_MFR_ADAPTIVE_DEADTIMES_REGION_1 (0xB5)

/* instantiate the command MFR_ADAPTIVE_DEADTIMES_REGION_1.
 */
extern PMBUS_CMD_t PMBUS_CMD_MFR_ADAPTIVE_DEADTIMES_REGION_1;
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIMES_REGION_1_DATA_LOOP0[24];  	// data array for command loop0
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIMES_REGION_1_DATA_LOOP1[24];    // data array for command loop1 (pointer if common)

#define PMBUS_CMDCODE_MFR_ADAPTIVE_DEADTIMES_REGION_2 (0xB6)

/* instantiate the command MFR_ADAPTIVE_DEADTIMES_REGION_2.
 */
extern PMBUS_CMD_t PMBUS_CMD_MFR_ADAPTIVE_DEADTIMES_REGION_2;
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIMES_REGION_2_DATA_LOOP0[24];  	// data array for command loop0
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIMES_REGION_2_DATA_LOOP1[24];    // data array for command loop1 (pointer if common)

#define PMBUS_CMDCODE_MFR_ADAPTIVE_DEADTIMES_REGION_3 (0xB7)

/* instantiate the command MFR_ADAPTIVE_DEADTIMES_REGION_3.
 */
extern PMBUS_CMD_t PMBUS_CMD_MFR_ADAPTIVE_DEADTIMES_REGION_3;
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIMES_REGION_3_DATA_LOOP0[24];  	// data array for command loop0
extern uint8_t	PMBUS_CMD_MFR_ADAPTIVE_DEADTIMES_REGION_3_DATA_LOOP1[24];    // data array for command loop1 (pointer if common)


void pmbus_mfr_autogen_init(void);

// external handle functions

#endif   //#endif /* _PMBUS_MFR_AUTOGEN_H_ */


